---

# packages for the current distribution
_pa_packages: "{{ pa_packages | powo.tools.distro(vars) }}"
_pa_service: "{{ pa_service | powo.tools.distro(vars) }}"
_pa_modules: "{{ pa_modules | powo.tools.distro(vars) }}"
