---

- name: install
  import_role:
    name: powo.archive
  vars:
    par_archive_destination_folder: "{{ pja_download_folder }}"
    par_archive_extraction_folder: "{{ _pja_item_install_folder }}"
    par_archive_url: "{{ _pja_item_download_url }}"
    par_archive_checksum: "{{ _pja_item_download_checksum }}"
    par_archive_strip: 1
    par_download_headers: "{{ _pja_headers }}"
