- name: firewalld.reload
  service:
    name: firewalld
    state: reloaded
  become: true
  become_user: root

- name: firewalld.restart
  service:
    name: firewalld
    state: restarted
  become: true
  become_user: root
