---

is_user_supplied: "{{ user is defined }}"
play_user: "{{ user | default(lookup('pipe', 'whoami')) }}"
play_uid: "{{ uid | default(lookup('pipe', 'id -u')) }}"
play_password: "{{ password | password_hash('sha512') | default(none) }}"
play_passphrase: "{{ passphrase | default(none) }}"
play_fullname: "{{ fullname | default(none) }}"
play_home: "{{ lookup('pipe', 'getent passwd ' + play_user).split(':')[5] }}"
play_all: false

postgresql_versions:
  - "12"
  - "13"
  - "14"
  - "15"

postgresql_cluster_clusters:
  - name: default
    path: /data/services/postgresql/12-default/
    postgresql_version: "12"
    port: 5434
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/13-default/
    postgresql_version: "13"
    port: 5435
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/14-default/
    postgresql_version: "14"
    port: 5436
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/15-default/
    postgresql_version: "15"
    port: 5437
    pg_hba: pg_hba_local.conf

apps_folder: "{{ play_home }}/Documents/apps"
tools_folder: "{{ play_home }}/Documents/tools"

# Java
bin_java: "{{ apps_folder }}/jdk-11/bin/java"
bin_java_8: "{{ apps_folder }}/jdk-8/bin/java"
bin_java_17: "{{ apps_folder }}/jdk-17/bin/java"

dir_jdk_8: "/usr/lib/jvm/{{ package_jdk8.basename }}"
dir_jdk_11: "/usr/lib/jvm/{{ package_jdk11.basename }}"
dir_jdk_17: "/usr/lib/jvm/{{ package_jdk17.basename }}"
bash_java_template: |
  export JAVA_HOME={{ bin_java | dirname | dirname | expanduser | quote }}
package_jdk8:
  package: java-1.8.0-openjdk
  basename: java-1.8.0-openjdk
package_jdk11:
  package: java-11-openjdk
  basename: java-11-openjdk
package_jdk17:
  package: java-17-openjdk
  basename: java-17-openjdk

# Maven
bin_maven: "{{ bin_maven_39 }}"
bin_maven_39: "{{ apps_folder }}/{{ bundle_maven_3_9_6.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bin_maven_38: "{{ apps_folder }}/{{ bundle_maven_3_8_8.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bash_maven_template: |
  export MAVEN_OPTS="-Xmx1024m"
bundle_maven_3_8_8:
  url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
  basename: maven-3.8.8.tar.gz
  checksum: sha512:332088670d14fa9ff346e6858ca0acca304666596fec86eea89253bd496d3c90deae2be5091be199f48e09d46cec817c6419d5161fb4ee37871503f472765d00
bundle_maven_3_9_6:
  url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
  basename: maven-3.9.6.tar.gz
  checksum: sha512:706f01b20dec0305a822ab614d51f32b07ee11d0218175e55450242e49d2156386483b506b3a4e8a03ac8611bae96395fd5eec15f50d3013d5deed6d1ee18224

# Tomcat
dir_tomcat_9: "{{ apps_folder }}/{{ bundle_tomcat_9_0_30.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
bundle_tomcat_9_0_30:
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
  checksum: sha512:40bf428a534816317e5e8732b679e6d73f6ed977aab4ac5e2b9eaf1eb087eaa68a18b0fd3da8c39ca4b96f5b6fd919dec84517abba0d5e797285ade934a92990
bundle_tomcat_9_0_84:
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz
  checksum: sha512:85a42ab5e7e4cb1923888e96a78a0f277a870d06e76147a95457878c124001c9a317eade4ad69c249a460ffe2cbefe894022b84389cdf33038bc456e3699c8e3

# Eclipse
bin_eclipse: "{{ apps_folder }}/{{ bundle_eclipse_java_202212b.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202212: "{{ apps_folder }}/{{ bundle_eclipse_java_202212b.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
bundle_eclipse_java_202212b:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2022-12/eclipse-java-extra-2022-12b-linux-gtk-x86_64.tar.gz
  checksum: sha256:47cf3e44d669ed3fe822fab047e6600ffbb464018e72f0411e082d5381215352
  desktop_name: Eclipse 22.12b (extra)
  vm: ""
eclipse_clean_basenames:
  - eclipse-java-extra-oxygen-1-linux-gtk-x86_64
  - eclipse-java-extra-oxygen-2-linux-gtk-x86_64
  - eclipse-java-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-rcp-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-java-extra-2018-09a-linux-gtk-x86_64
  - eclipse-java-extra-2018-12a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03b-linux-gtk-x86_64
  - eclipse-java-extra-2019-06a-linux-gtk-x86_64
  - eclipse-java-extra-2019-09a-linux-gtk-x86_64
  - eclipse-java-extra-2019-12a-linux-gtk-x86_64
  - eclipse-java-extra-2020-03a-linux-gtk-x86_64
  - eclipse-java-extra-2020-06a-linux-gtk-x86_64
  - eclipse-java-extra-2020-09a-linux-gtk-x86_64
  - eclipse-java-extra-2020-12a-linux-gtk-x86_64
  - eclipse-java-extra-2021-03a-linux-gtk-x86_64
  - eclipse-java-extra-2021-06a-linux-gtk-x86_64
  - eclipse-java-extra-2021-09a-linux-gtk-x86_64
  - eclipse-java-extra-2021-12a-linux-gtk-x86_64
  - eclipse-java-extra-2022-03a-linux-gtk-x86_64
  - eclipse-java-extra-2022-06a-linux-gtk-x86_64
  - eclipse-java-extra-2022-09a-linux-gtk-x86_64
  - eclipse-java-extra-2022-12a-linux-gtk-x86_64

# Luke
bundle_luke_520:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.2.0/luke-5.2.0-luke-release.zip
  checksum: sha256:1f1aec4ca5177c9f1d61d013077fba2e75baff167130eb0187963c81e6b77dae
  desktop_name: Luke 5.2.0
bundle_luke_530:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.3.0/luke-5.3.0-luke-release.zip
  checksum: sha256:34e424fd3fbf1a76205696f71b6c6b0d8eeac79d2289007badca12a1926efbfe
  desktop_name: Luke 5.3.0
bundle_luke_540:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.4.0/luke-5.4.0-luke-release.zip
  checksum: sha256:ff83e59a66fe76f6b5ff2bbef6cbf10e29bb58cfb3107a9f2e083c61b39f923f
  desktop_name: Luke 5.4.0
bundle_luke_550:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.5.0/luke-5.5.0-luke-release.zip
  checksum: sha256:f219c3eb7efd5a67c393f9c581aa7f577d43cb8697bb16d290949200b6276a23
  desktop_name: Luke 5.5.0
bundle_luke_600:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.0.0/luke-6.0.0-luke-release.zip
  checksum: sha256:cb678d5135299b4aff3ef1c6c0f532e33689775bed196f5d465b51c434b4e107
  desktop_name: Luke 6.0.0
bundle_luke_610:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.1.0/luke-6.1.0-luke-release.zip
  checksum: sha256:737898b4159a9184347313bd5bd61d05a211878cfa22b0d57eaffb169be8bcc2
  desktop_name: Luke 6.1.0
bundle_luke_621:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.2.1/luke-6.2.1-luke-release.zip
  checksum: sha256:99dc5d30dea557afd2a7ffd64619f4eb3f34ac9ac958a4619acd8dde5ce6ec4c
  desktop_name: Luke 6.2.1
bundle_luke_630:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.3.0/luke-6.3.0-luke-release.zip
  checksum: sha256:163d6b5eeaf2269a00ba8c856adba708e3dd8b1b7c204ae9a981b324bebd7d7f
  desktop_name: Luke 6.3.0
  strip_path: luke-6.3.0
bundle_luke_641:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.4.1/luke-6.4.1-luke-release.zip
  checksum: sha256:12ba7dd85158d11fe4197f95bb1bf7ee6c5ab810c85a4df4f14b2b5b3c63ed81
  desktop_name: Luke 6.4.1
  strip_path: luke-6.4.1
bundle_luke_650:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.5.0/luke-6.5.0-luke-release.zip
  checksum: sha256:6af4455385212db7f68c2d7042977a763dbd57094168a0288aa3d509e443f6fb
  desktop_name: Luke 6.5.0
  strip_path: luke-6.5.0
bundle_luke_660:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.6.0/luke-6.6.0-luke-release.zip
  checksum: sha256:68154a592d1829e15e1795c50d6b923a2ee59f0469303fb57b53022c14eb7dd0
  desktop_name: Luke 6.6.0
  strip_path: luke-6.6.0
bundle_luke_710:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.1.0/luke-7.1.0-luke-release.zip
  checksum: sha256:fa71d06f12074de8ae2e063a92b676f6f3789f72dd83a362bcfa4f4466111d72
  desktop_name: Luke 7.1.0
  strip_path: luke-7.1.0
bundle_luke_720:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.2.0/luke-7.2.0-luke-release.zip
  checksum: sha256:2485b3d09d2bfc524f1fc4d3e9ad97c8e00aa68f9a25354631ce0ac14719e1c1
  desktop_name: Luke 7.2.0
  strip_path: luke-7.2.0
bundle_luke_731:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.3.1/luke-javafx-7.3.1-luke-release.zip
  checksum: sha256:8597c1a58d4442bb68a23d25126f7c02586000d7d1a3778eb20370a42439638b
  desktop_name: Luke 7.3.1
  strip_path: luke-7.3.1
bundle_luke_740:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.4.0/luke-javafx-7.4.0-luke-release.zip
  checksum: sha256:934098b9533ff06f602ae703643b37c003d2cf086fc7c572998f9b9e3e2cd55b
  desktop_name: Luke 7.4.0
  strip_path: luke-7.4.0
bundle_luke_750:
  url: https://github.com/DmitryKey/luke/releases/download/luke-javafx-7.5.0/luke-javafx-7.5.0-luke-release.zip
  checksum: sha256:927787b166277cfa1d511a8b4143116b7a81eb9b075944e2c7b1d2bc442bec2f
  desktop_name: Luke 7.5.0
  strip_path: luke-javafx-7.5.0
