---

is_user_supplied: "{{ user is defined }}"
play_user: "{{ user | default(lookup('pipe', 'whoami')) }}"
play_uid: "{{ uid | default(lookup('pipe', 'id -u')) }}"
play_password: "{{ password | password_hash('sha512') | default(none) }}"
play_passphrase: "{{ passphrase | default(none) }}"
play_fullname: "{{ fullname | default(none) }}"
play_home: "{{ lookup('pipe', 'getent passwd ' + play_user).split(':')[5] }}"

apps_folder: "{{ play_home }}/Documents/apps"
tools_folder: "{{ play_home }}/Documents/tools"

# Java
bin_java: "{{ apps_folder }}/jdk-8/bin/java"
bin_java_11: "{{ apps_folder }}/jdk-11/bin/java"
dir_jdk_8: "/usr/lib/jvm/{{ package_jdk8.basename }}"
dir_jdk_11: "/usr/lib/jvm/{{ package_jdk11.basename }}"
bash_java_template: |
  export JAVA_HOME={{ bin_java | dirname | dirname | expanduser | quote }}
package_jdk8:
  package: java-1.8.0-openjdk
  basename: java-1.8.0-openjdk
package_jdk11:
  package: java-11-openjdk
  basename: java-11-openjdk

# Maven
bin_maven: "{{ bin_maven_38 }}"
bin_maven_36: "{{ apps_folder }}/{{ bundle_maven_3_6_3.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bin_maven_38: "{{ apps_folder }}/{{ bundle_maven_3_8_4.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bash_maven_template: |
  export MAVEN_OPTS="-Xmx1024m"
bundle_maven_3_8_4:
  url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
  basename: maven-3.8.4.tar.gz
  checksum: sha512:a9b2d825eacf2e771ed5d6b0e01398589ac1bfa4171f36154d1b5787879605507802f699da6f7cfc80732a5282fd31b28e4cd6052338cbef0fa1358b48a5e3c8
bundle_maven_3_6_3:
  url: https://dlcdn.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  basename: maven-3.6.3.tar.gz
  checksum: sha512:c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
bundle_maven_3_5_4:
  url: https://dlcdn.apache.org/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
  basename: maven-3.5.4.tar.gz
  checksum: sha256:ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d
bundle_maven_3_3_9:
  url: https://dlcdn.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  checksum: md5:516923b3955b6035ba6b0a5b031fbd8b
  basename: maven-3.3.9.tar.gz

# Tomcat
dir_tomcat_7: "{{ apps_folder }}/{{ bundle_tomcat_7_0_90.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
dir_tomcat_8: "{{ apps_folder }}/{{ bundle_tomcat_8_0_53.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
dir_tomcat_85: "{{ apps_folder }}/{{ bundle_tomcat_8_5_32.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
dir_tomcat_9: "{{ apps_folder }}/{{ bundle_tomcat_9_0_10.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
bundle_tomcat_7_0_90:
  url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.90/bin/apache-tomcat-7.0.90.tar.gz
  checksum: sha512:c7a47135b99684425260cd906cf5c9a5226837d3681d84ae4e3bb199068e97f0e63d07393d91ca0436204a1dc92bf9bd9a4a1c4c893187703e023503bbd81901
bundle_tomcat_8_0_53:
  url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.53/bin/apache-tomcat-8.0.53.tar.gz
  checksum: sha512:cd8a4e48a629a2f2bb4ce6b101ebcce41da52b506064396ec1b2915c0b0d8d82123091242f2929a649bcd8b65ecf6cd1ab9c7d90ac0e261821097ab6fbe22df9
bundle_tomcat_8_5_32:
  url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz
  checksum: sha512:fc010f4643cb9996cad3812594190564d0a30be717f659110211414faf8063c61fad1f18134154084ad3ddfbbbdb352fa6686a28fbb6402d3207d4e0a88fa9ce
bundle_tomcat_9_0_10:
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
  checksum: sha512:ecdee920fcb75bf30cd87c350e0732e8fa566911cd16cf2759689edd324ebac911c0d154e79ffc67e948b29eacc49c88dadc5954383d3c4af2fdb952f3d1c371

# Eclipse
bin_eclipse: "{{ apps_folder }}/{{ bundle_eclipse_java_201906a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_201906: "{{ apps_folder }}/{{ bundle_eclipse_java_201906a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_201909: "{{ apps_folder }}/{{ bundle_eclipse_java_201909a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_201912: "{{ apps_folder }}/{{ bundle_eclipse_java_201912a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202003: "{{ apps_folder }}/{{ bundle_eclipse_java_202003a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202006: "{{ apps_folder }}/{{ bundle_eclipse_java_202006a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202009: "{{ apps_folder }}/{{ bundle_eclipse_java_202009a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202012: "{{ apps_folder }}/{{ bundle_eclipse_java_202012a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202103: "{{ apps_folder }}/{{ bundle_eclipse_java_202103a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202106: "{{ apps_folder }}/{{ bundle_eclipse_java_202106a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202109: "{{ apps_folder }}/{{ bundle_eclipse_java_202109a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202112: "{{ apps_folder }}/{{ bundle_eclipse_java_202112a.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
bundle_eclipse_java_473:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/oxygen/eclipse-java-extra-oxygen-3-linux-gtk-x86_64.tar.gz
  checksum: sha256:a9f0a7a9e5ed4bba9a25b18335719758316c2c6e16c7fe33c10025069abdec0f
  desktop_name: Eclipse 4.7.3 (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_48:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/photon/eclipse-java-extra-photon-linux-gtk-x86_64.tar.gz
  checksum: sha256:7820930641f22a9b70011fcbd3a8c67796f67998a5831dfc4a7b4a8d680eb905
  desktop_name: Eclipse 4.8 (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_48b:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/photon/eclipse-java-extra-photon-4.8b-linux-gtk-x86_64.tar.gz
  checksum: sha256:03771a92694e58d20711495e5b812db0bf965d300985638d47f753a4823d3467
  desktop_name: Eclipse 4.8b (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_201809b:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2018-09/eclipse-java-extra-2018-09b-linux-gtk-x86_64.tar.gz
  checksum: sha256:d5e932c115b55ada68db49f934d66315e6cc76890f68f946ffce99cb9787678e
  desktop_name: Eclipse 2018-09b (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_201812a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2018-12/eclipse-java-extra-2018-12a-linux-gtk-x86_64.tar.gz
  checksum: sha256:fb2ccc899a0f6487cf9892a8dcbc26768dfa48f4e1535336fb6746afcfa44ed3
  desktop_name: Eclipse 2018-12a (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_201903b:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2019-03/eclipse-java-extra-2019-03b-linux-gtk-x86_64.tar.gz
  checksum: sha256:ec1c5ce5ba75b50f2d408c94ea749eeb004530eec0201a25b07d0ba933485ca4
  desktop_name: Eclipse 19.03b (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_201906a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2019-06/eclipse-java-extra-2019-06a-linux-gtk-x86_64.tar.gz
  checksum: sha256:bc519ccdbcc392689d98be26e2fe29dbe7704602d5474dd0a1121e844ef60692
  desktop_name: Eclipse 19.06a (extra)
  vm: "{{ bin_java }}"
bundle_eclipse_java_201909a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2019-09/eclipse-java-extra-2019-09a-linux-gtk-x86_64.tar.gz
  checksum: sha256:08372b85c216d2fcf61313d32c9b28f7062a4d101b26c02c1e080bac7679c3f4
  desktop_name: Eclipse 19.09a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_201912a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2019-12/eclipse-java-extra-2019-12a-linux-gtk-x86_64.tar.gz
  checksum: sha256:4af2d756f178f357864a635debdb3c53f6d3db41db687b619faa3d21e17f335e
  desktop_name: Eclipse 19.12a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202003a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2020-03/eclipse-java-extra-2020-03a-linux-gtk-x86_64.tar.gz
  checksum: sha256:7d6d4319d966dc1d34fbbb8471950d7a2a6735bb55b849306f93b01050325336
  desktop_name: Eclipse 20.03a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202006a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2020-06/eclipse-java-extra-2020-06a-linux-gtk-x86_64.tar.gz
  checksum: sha256:76218d47d23b2ee6cf94be97d2aad5ffba4782e2e536f1813e27614ad02ad312
  desktop_name: Eclipse 20.06a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202009a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2020-09/eclipse-java-extra-2020-09a-linux-gtk-x86_64.tar.gz
  checksum: sha256:e03f4544839028001026d5bec3871e54a2ec47bb03ab19e6130425766443a08a
  desktop_name: Eclipse 20.09a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202012a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2020-12/eclipse-java-extra-2020-12a-linux-gtk-x86_64.tar.gz
  checksum: sha256:31e663ce1c7e42be372050282234c3a18117cc50d19d95ace4dd76a2b6f8ba59
  desktop_name: Eclipse 20.12a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202103a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2021-03/eclipse-java-extra-2021-03a-linux-gtk-x86_64.tar.gz
  checksum: sha256:46255e4a725452d96a906833e82bd5926c0dc233eabc024d449a7a94e0cf7718
  desktop_name: Eclipse 21.03a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202106a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2021-06/eclipse-java-extra-2021-06a-linux-gtk-x86_64.tar.gz
  checksum: sha256:4201f50e46243420015e0d44a83854b982e1a251e46adfcd6cb8a1d39c0acccc
  desktop_name: Eclipse 21.06a (extra)
  # JVM 16 not compatible with sonar - https://community.sonarsource.com/t/maven-sonar-scanner-not-working-with-jdk-16/40699
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202109a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2021-09/eclipse-java-extra-2021-09a-linux-gtk-x86_64.tar.gz
  checksum: sha256:4f5a07f95654f86175d96f756e8b44fd253bb8af9d4a631e3a0e4fd3c25a7989
  desktop_name: Eclipse 21.09a (extra)
  vm: "{{ bin_java_11 }}"
bundle_eclipse_java_202112a:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2021-12/eclipse-java-extra-2021-12a-linux-gtk-x86_64.tar.gz
  checksum: sha256:8a2efdf0e436518cebffcda3e35c89a7cd1a05d6ee22ae3d5079202b5c0d60ed
  desktop_name: Eclipse 21.12a (extra)
  vm: "{{ bin_java_11 }}"
eclipse_clean_basenames:
  - eclipse-java-extra-oxygen-1-linux-gtk-x86_64
  - eclipse-java-extra-oxygen-2-linux-gtk-x86_64
  - eclipse-java-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-rcp-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-java-extra-2018-09a-linux-gtk-x86_64
  - eclipse-java-extra-2018-12a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03b-linux-gtk-x86_64
  - eclipse-java-extra-2019-09a-linux-gtk-x86_64
  - eclipse-java-extra-2019-12a-linux-gtk-x86_64
  - eclipse-java-extra-2020-03a-linux-gtk-x86_64
  - eclipse-java-extra-2020-06a-linux-gtk-x86_64
  - eclipse-java-extra-2020-09a-linux-gtk-x86_64
  - eclipse-java-extra-2020-12a-linux-gtk-x86_64
  - eclipse-java-extra-2021-03a-linux-gtk-x86_64

# Luke
bundle_luke_520:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.2.0/luke-5.2.0-luke-release.zip
  checksum: sha256:1f1aec4ca5177c9f1d61d013077fba2e75baff167130eb0187963c81e6b77dae
  desktop_name: Luke 5.2.0
bundle_luke_530:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.3.0/luke-5.3.0-luke-release.zip
  checksum: sha256:34e424fd3fbf1a76205696f71b6c6b0d8eeac79d2289007badca12a1926efbfe
  desktop_name: Luke 5.3.0
bundle_luke_540:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.4.0/luke-5.4.0-luke-release.zip
  checksum: sha256:ff83e59a66fe76f6b5ff2bbef6cbf10e29bb58cfb3107a9f2e083c61b39f923f
  desktop_name: Luke 5.4.0
bundle_luke_550:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.5.0/luke-5.5.0-luke-release.zip
  checksum: sha256:f219c3eb7efd5a67c393f9c581aa7f577d43cb8697bb16d290949200b6276a23
  desktop_name: Luke 5.5.0
bundle_luke_600:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.0.0/luke-6.0.0-luke-release.zip
  checksum: sha256:cb678d5135299b4aff3ef1c6c0f532e33689775bed196f5d465b51c434b4e107
  desktop_name: Luke 6.0.0
bundle_luke_610:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.1.0/luke-6.1.0-luke-release.zip
  checksum: sha256:737898b4159a9184347313bd5bd61d05a211878cfa22b0d57eaffb169be8bcc2
  desktop_name: Luke 6.1.0
bundle_luke_621:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.2.1/luke-6.2.1-luke-release.zip
  checksum: sha256:99dc5d30dea557afd2a7ffd64619f4eb3f34ac9ac958a4619acd8dde5ce6ec4c
  desktop_name: Luke 6.2.1
bundle_luke_630:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.3.0/luke-6.3.0-luke-release.zip
  checksum: sha256:163d6b5eeaf2269a00ba8c856adba708e3dd8b1b7c204ae9a981b324bebd7d7f
  desktop_name: Luke 6.3.0
  strip_path: luke-6.3.0
bundle_luke_641:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.4.1/luke-6.4.1-luke-release.zip
  checksum: sha256:12ba7dd85158d11fe4197f95bb1bf7ee6c5ab810c85a4df4f14b2b5b3c63ed81
  desktop_name: Luke 6.4.1
  strip_path: luke-6.4.1
bundle_luke_650:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.5.0/luke-6.5.0-luke-release.zip
  checksum: sha256:6af4455385212db7f68c2d7042977a763dbd57094168a0288aa3d509e443f6fb
  desktop_name: Luke 6.5.0
  strip_path: luke-6.5.0
bundle_luke_660:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.6.0/luke-6.6.0-luke-release.zip
  checksum: sha256:68154a592d1829e15e1795c50d6b923a2ee59f0469303fb57b53022c14eb7dd0
  desktop_name: Luke 6.6.0
  strip_path: luke-6.6.0
bundle_luke_710:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.1.0/luke-7.1.0-luke-release.zip
  checksum: sha256:fa71d06f12074de8ae2e063a92b676f6f3789f72dd83a362bcfa4f4466111d72
  desktop_name: Luke 7.1.0
  strip_path: luke-7.1.0
bundle_luke_720:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.2.0/luke-7.2.0-luke-release.zip
  checksum: sha256:2485b3d09d2bfc524f1fc4d3e9ad97c8e00aa68f9a25354631ce0ac14719e1c1
  desktop_name: Luke 7.2.0
  strip_path: luke-7.2.0
bundle_luke_731:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.3.1/luke-javafx-7.3.1-luke-release.zip
  checksum: sha256:8597c1a58d4442bb68a23d25126f7c02586000d7d1a3778eb20370a42439638b
  desktop_name: Luke 7.3.1
  strip_path: luke-7.3.1
bundle_luke_740:
  url: https://github.com/DmitryKey/luke/releases/download/luke-7.4.0/luke-javafx-7.4.0-luke-release.zip
  checksum: sha256:934098b9533ff06f602ae703643b37c003d2cf086fc7c572998f9b9e3e2cd55b
  desktop_name: Luke 7.4.0
  strip_path: luke-7.4.0
bundle_luke_750:
  url: https://github.com/DmitryKey/luke/releases/download/luke-javafx-7.5.0/luke-javafx-7.5.0-luke-release.zip
  checksum: sha256:927787b166277cfa1d511a8b4143116b7a81eb9b075944e2c7b1d2bc442bec2f
  desktop_name: Luke 7.5.0
  strip_path: luke-javafx-7.5.0
