---

is_user_supplied: "{{ user is defined }}"
play_user: "{{ user | default(lookup('pipe', 'whoami')) }}"
play_uid: "{{ uid | default(lookup('pipe', 'id -u')) }}"
play_password: "{{ password | password_hash('sha512') | default(none) }}"
play_passphrase: "{{ passphrase | default(none) }}"
play_fullname: "{{ fullname | default(none) }}"
play_home: "{{ lookup('pipe', 'getent passwd ' + play_user).split(':')[5] }}"
play_all: false

postgresql_versions:
  - "13"
  - "14"
  - "15"
  - "16"

postgresql_cluster_clusters:
  - name: default
    path: /data/services/postgresql/13-default/
    postgresql_version: "13"
    port: 5435
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/14-default/
    postgresql_version: "14"
    port: 5436
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/15-default/
    postgresql_version: "15"
    port: 5437
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/16-default/
    postgresql_version: "16"
    port: 5438
    pg_hba: pg_hba_local.conf

postgresql_clean_versions:
  - "9.6"
  - "10"
  - "11"
  - "12"

postgresql_clean_cluster_clusters:
  - name: default
    path: /data/services/postgresql/9.6-default/
    postgresql_version: "9.6"
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/10-default/
    postgresql_version: "10"
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/11-default/
    postgresql_version: "11"
    pg_hba: pg_hba_local.conf
  - name: default
    path: /data/services/postgresql/12-default/
    postgresql_version: "12"
    pg_hba: pg_hba_local.conf

apps_folder: "{{ play_home }}/Documents/apps"
tools_folder: "{{ play_home }}/Documents/tools"

# Java
bin_java: "{{ apps_folder }}/jdk-11/bin/java"
bin_java_8: "{{ apps_folder }}/jdk-8/bin/java"
bin_java_17: "{{ apps_folder }}/jdk-17/bin/java"

dir_jdk_11: "/usr/lib/jvm/{{ (package_jdk11 | distro(vars)).basename }}"
dir_jdk_17: "/usr/lib/jvm/{{ (package_jdk17 | distro(vars)).basename }}"
bash_java_template: |
  export JAVA_HOME={{ bin_java | dirname | dirname | expanduser | quote }}
package_jdk11:
  Fedora_41:
    package: java-11-openjdk
    basename: java-11-openjdk
  Fedora:
    package: temurin-11-jdk
    basename: temurin-11-jdk
package_jdk17:
  Fedora_41:
    package: java-17-openjdk
    basename: java-17-openjdk
  Fedora:
    package: temurin-17-jdk
    basename: temurin-17-jdk

# Maven
bin_maven: "{{ bin_maven_39 }}"
bin_maven_39: "{{ apps_folder }}/{{ bundle_maven_3_9_6.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bin_maven_38: "{{ apps_folder }}/{{ bundle_maven_3_8_8.basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/bin/mvn"
bash_maven_template: |
  export MAVEN_OPTS="-Xmx1024m"
bundle_maven_3_8_8:
  url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
  basename: maven-3.8.8.tar.gz
  checksum: sha512:332088670d14fa9ff346e6858ca0acca304666596fec86eea89253bd496d3c90deae2be5091be199f48e09d46cec817c6419d5161fb4ee37871503f472765d00
bundle_maven_3_9_6:
  url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
  basename: maven-3.9.6.tar.gz
  checksum: sha512:706f01b20dec0305a822ab614d51f32b07ee11d0218175e55450242e49d2156386483b506b3a4e8a03ac8611bae96395fd5eec15f50d3013d5deed6d1ee18224

# Tomcat
dir_tomcat_9: "{{ apps_folder }}/{{ bundle_tomcat_9_0_30.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}"
bundle_tomcat_9_0_30:
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
  checksum: sha512:40bf428a534816317e5e8732b679e6d73f6ed977aab4ac5e2b9eaf1eb087eaa68a18b0fd3da8c39ca4b96f5b6fd919dec84517abba0d5e797285ade934a92990
bundle_tomcat_9_0_84:
  url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz
  checksum: sha512:85a42ab5e7e4cb1923888e96a78a0f277a870d06e76147a95457878c124001c9a317eade4ad69c249a460ffe2cbefe894022b84389cdf33038bc456e3699c8e3

# Eclipse
bin_eclipse: "{{ apps_folder }}/{{ bundle_eclipse_java_202212b.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
dir_eclipse_202212: "{{ apps_folder }}/{{ bundle_eclipse_java_202212b.url | basename | regex_replace('(\\.[a-z]{1,3})*$', '') }}/"
bundle_eclipse_java_202212b:
  url: https://nexus.tools.kobalt.fr/repository/eclipse/2022-12/eclipse-java-extra-2022-12b-linux-gtk-x86_64.tar.gz
  checksum: sha256:47cf3e44d669ed3fe822fab047e6600ffbb464018e72f0411e082d5381215352
  desktop_name: Eclipse 22.12b (extra)
  vm: ""
eclipse_clean_basenames:
  - eclipse-java-extra-oxygen-1-linux-gtk-x86_64
  - eclipse-java-extra-oxygen-2-linux-gtk-x86_64
  - eclipse-java-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-rcp-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-java-extra-2018-09a-linux-gtk-x86_64
  - eclipse-java-extra-2018-12a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03a-linux-gtk-x86_64
  - eclipse-java-extra-2019-03b-linux-gtk-x86_64
  - eclipse-java-extra-2019-06a-linux-gtk-x86_64
  - eclipse-java-extra-2019-09a-linux-gtk-x86_64
  - eclipse-java-extra-2019-12a-linux-gtk-x86_64
  - eclipse-java-extra-2020-03a-linux-gtk-x86_64
  - eclipse-java-extra-2020-06a-linux-gtk-x86_64
  - eclipse-java-extra-2020-09a-linux-gtk-x86_64
  - eclipse-java-extra-2020-12a-linux-gtk-x86_64
  - eclipse-java-extra-2021-03a-linux-gtk-x86_64
  - eclipse-java-extra-2021-06a-linux-gtk-x86_64
  - eclipse-java-extra-2021-09a-linux-gtk-x86_64
  - eclipse-java-extra-2021-12a-linux-gtk-x86_64
  - eclipse-java-extra-2022-03a-linux-gtk-x86_64
  - eclipse-java-extra-2022-06a-linux-gtk-x86_64
  - eclipse-java-extra-2022-09a-linux-gtk-x86_64
  - eclipse-java-extra-2022-12a-linux-gtk-x86_64
  - eclipse-java-extra-2022-12b-linux-gtk-x86_64

# Luke
bundle_luke_550:
  url: https://github.com/DmitryKey/luke/releases/download/luke-5.5.0/luke-5.5.0-luke-release.zip
  checksum: sha256:f219c3eb7efd5a67c393f9c581aa7f577d43cb8697bb16d290949200b6276a23
  desktop_name: Luke 5.5.0
  bin_path:
bundle_luke_660:
  url: https://github.com/DmitryKey/luke/releases/download/luke-6.6.0/luke-6.6.0-luke-release.zip
  checksum: sha256:68154a592d1829e15e1795c50d6b923a2ee59f0469303fb57b53022c14eb7dd0
  desktop_name: Luke 6.6.0
  strip_path: luke-6.6.0
  bin_path:
bundle_luke_750:
  url: https://github.com/DmitryKey/luke/releases/download/luke-swing-7.5.0/luke-swing-7.5.0-luke-release.zip
  checksum: sha256:7ae709dd92fbd01740b1f196165dd15102a088507791b8476354981c2436e565
  desktop_name: Luke 7.5.0
  strip_path: luke-swing-7.5.0
  bin_path:
bundle_luke_811:
  url: https://archive.apache.org/dist/lucene/java/8.11.3/lucene-8.11.3.tgz
  checksum: sha256:8a03d7a71bc5b85eac7497855a1f02222f5ac7811cdd75cc46766993738df0f4
  desktop_name: Luke 8.11.3
  strip_path: lucene-8.11.3
  bin_path: luke/
bundle_luke_912:
  url: https://dlcdn.apache.org/lucene/java/9.12.1/lucene-9.12.1.tgz
  checksum: sha512:83996ad2a71b22a76c7a9c1803d829e1e58a436c585cfd52850855620144cd99441017dc3e36877818989c1c7aa0cc9ae0f38581ae1c652a47ff2f498af13a9e
  desktop_name: Luke 9.12.1
  strip_path: lucene-9.12.1
