---

_pja_package_name: "{{ _pja_temurin_package_name if 'temurin' in item.package else _pja_openjdk_package_name }}"

# temurin : only one package name
_pja_temurin_package_name:
  - "{{ item.package }}"

# not-temurin : 3 packages
_pja_openjdk_package_name:
  - "{{ item.package }}-devel"
  - "{{ item.package }}-headless"
  - "{{ item.package }}-src"
