---

- name: directories
  with_items: "{{ psy_directories }}"
  file:
    path: "{{ item }}"
    force: true
    state: directory

- name: symlinks
  with_items: "{{ psy_symlinks }}"
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    force: true
    state: link


- name: clean symlinks
  with_items: "{{ psy_clean_symlinks }}"
  file:
    path: "{{ item }}"
    state: absent