---

- name: "group creation"
  group:
    name: "{{ pu_group }}"
    gid: "{{ pu_gid }}"
    system: false

- name: "user creation"
  user:
    name: "{{ pu_user }}"
    uid: "{{ pu_uid }}"
    shell: "{{ pu_shell }}"
    group: "{{ pu_group }}"
    groups: "{{ _pu_groups }}"
    append: true
    comment: "{{ pu_fullname if pu_fullname else omit }}"
    createhome: true
    password: "{{ pu_password if pu_password else omit }}"
    update_password: on_create
