---

pec_install_base_folder: "{{ xxx_mandatory }}"

pec_clean_basenames:
  - eclipse-java-extra-oxygen-1-linux-gtk-x86_64
  - eclipse-java-extra-oxygen-2-linux-gtk-x86_64
  - eclipse-java-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-rcp-extra-photon-RC1-linux-gtk-x86_64
  - eclipse-java-extra-2018-09a-linux-gtk-x86_64
  - eclipse-java-extra-2018-12a-linux-gtk-x86_64
