---

- name: install
  import_role:
    name: powo.archive
  vars:
    par_archive_destination_folder: "{{ pma_download_folder }}"
    par_archive_extraction_folder: "{{ _pma_item_install_folder }}"
    par_archive_url: "{{ _pma_item_download_url }}"
    par_archive_checksum: "{{ _pma_item_download_checksum }}"
    par_archive_strip: 1
