---

# rewrite key install without apt-key (that is deprecated ?)
- name: dirmngr utility
  package:
    name: dirmngr

- name: google chrome repository keys
  with_items:
    - EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    - 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
  apt_key:
    id: "{{ item }}"
    keyserver: keys.gnupg.net

- name: google chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
