---

- name: privileged
  become: true
  become_user: root
  block:
    - name: ansible/python package bindings
      import_tasks: checks.package.yml
      when: pc_package

    - name: ansible/python security bindings
      import_tasks: checks.security.yml
      when: pc_security
