
- import_tasks: nexus-yum.yml
  when: ansible_distribution == 'Fedora'

- import_tasks: packagekit.yml
  when: ansible_distribution == 'Fedora'

- import_tasks: docker.yml
  when: ansible_distribution == 'Fedora'

- import_tasks: dleyna.yml
  when: ansible_distribution == 'Fedora'

- import_role:
    name: powo.rpmfusion
  when: ansible_os_family == 'RedHat'

- import_role:
    name: epel
  when: ansible_distribution in ['RedHat', 'CentOS']

- import_tasks: bitwarden.yml
  when: ansible_distribution == 'Fedora'
- import_tasks: restic.yml
  when: ansible_distribution == 'Fedora'
- import_tasks: eclipse.yml
  when: ansible_distribution == 'Fedora'

- import_tasks: ppa-nextcloud.yml
  become: true
  become_user: root
  when: ansible_distribution == 'Ubuntu'

- import_tasks: code-rpm.yml
  become: true
  become_user: root
  when: ansible_os_family == 'RedHat'

- import_tasks: code-deb.yml
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'

- import_tasks: flameshot.yml
  become: true
  become_user: root

- import_tasks: mailhog.yml
  become: true
  become_user: root
  when: ansible_os_family == 'RedHat'
  tags:
  - mailhog

- import_tasks: abrt.yml
  become: true
  become_user: root
  when: ansible_os_family == 'RedHat'

- name: privileged
  become: true
  become_user: root
  block:
  - name: misc
    package:
      name: "{{ _pmi_packages }}"

  - name: ssh
    service:
      name: "{{ _pmi_ssh_service }}"
      state: started
      enabled: true
