---

- hosts: localhost
  roles:
    - name: user
      pu_create: "{{ is_user_supplied }}"
      pu_user: "{{ play_user }}"
      pu_uid: "{{ play_uid }}"
      pu_password: "{{ play_password }}"
      pu_passphrase: "{{ play_passphrase }}"
      pu_fullname: "{{ play_fullname }}"
      pu_sudo: true
      pu_profiles:
        - filename: 50-java.conf
          template: "{{ bash_java_template }}"
        - filename: 50-maven.conf
          template: "{{ bash_maven_template }}"
