---

- name: disable dnf5daemon-server
  ansible.builtin.systemd:
    name: dnf5daemon-server
    enabled: false
    masked: true
    state: stopped
  become: true
  become_user: root

- name: dnf5daemon-server clear cache
  file:
    state: absent
    path: /var/cache/dnf5daemon-server
  become: true
  become_user: root
