---

- name: docker
  package:
    name:
      - moby-engine
      - docker-compose
      # Fedora 42: on a eu le cas du poste de Corinne sans
      # la commande disponible
      - iptables-nft
  become: true
  become_user: root

- name: docker group
  user:
    name: "{{ play_user }}"
    groups: docker
    append: true
  become: true
  become_user: root

- name: docker service
  service:
    name: docker
    enabled: true
    state: started
  become: true
  become_user: root

- name: docker config path
  file:
    path: /etc/docker
    state: directory
  become: true
  become_user: root

# Enforce default ip address for listen
# as docker does not honor firewall setup
- name: docker config
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "ip": "127.0.0.1"
      }
  become: true
  become_user: root

- name: docker content directory
  shell: |
    set -e
    docker stop $( docker ps --format '{{ '{{' }}.ID{{ '}}' }}' ) || true
    systemctl stop docker docker.socket
    [ -d /var/lib/docker ] || { echo "/var/lib/docker is missing"; exit 1; }
    mv -t /home /var/lib/docker
    ln -sT /home/docker /var/lib/docker
    systemctl start docker docker.socket
  args:
    creates: /home/docker
    executable: /usr/bin/bash
  become: true
  become_user: root
  when: move_docker
