---

- name: disable packagekit
  ansible.builtin.systemd:
    name: packagekit
    enabled: false
    masked: true
  become: true
  become_user: root

- name: packagekit clear cache
  file:
    state: absent
    path: /var/cache/PackageKit
  become: true
  become_user: root
