---

- name: install
  import_role:
    name: powo.archive
  vars:
    par_archive_destination_folder: "{{ vvm_download_folder }}"
    par_archive_extraction_folder: "{{ _vvm_item_install_folder | dirname }}"
    par_archive_url: "{{ _vvm_item_download_url }}"
    par_archive_checksum: "{{ _vvm_item_download_checksum }}"

- name: desktop
  copy:
    content: |
      #jinja2:trim_blocks: False
      [Desktop Entry]
      Name=VisualVM {{ _vvm_item_version }}/{{ jdkitem.version }}
      Exec={{ _vvm_item_visualvm_bin | expanduser | quote }} --jdkhome {{ jdkitem.path | quote }}
      Type=Application
      Description=VisualVM
      Icon={{ _vvm_item_visualvm_icon | expanduser }}
    dest: ~/.local/share/applications/visualvm-{{ _vvm_item_version }}-java-{{ jdkitem.version }}.desktop
  with_items: "{{ _vvm_item_jdkhomes }}"
  loop_control:
    loop_var: jdkitem

